### ISSUE TITLE
Não funcionando em alguns bancos

### ISSUE THREAD

**Issue by RafaelUSA7** [mattnicee7/PixQRCodeGenerator#1]
Fiz o teste do QRCode e PIX Copia e Cola e não está funcionando em alguns bancos dependendo da chave pix

Com chave CPF não está funcionando no Banco Satander
Com chave E-mail não está funcionando nos Bancos: Satander, Neon, PagBank
Nos bancos NuBank e Inter ambos funcionam normalmente

Testei com o gerador do site https://www.gerarpix.com.br/ com as mesmas configurações e nele funciona normalmente todos, comparei o código do QRCode e a única diferença são ós últimos 4 digitos

**Comment by mattnicee7** [comment]
Obrigado pelo reporte.

Os 4 últimos dígitos são o checksum, irei verificar o que está acontecendo e volto com uma resposta em breve. Caso queira dar um pull-request também é muito bem vindo.

**Comment by mattnicee7** [comment]
Você poderia deixar alguns códigos de PIX e Copia e Cola que você gerou com o framework e com o site https://www.gerarpix.com.br/ e não deu certo nos bancos citados? Em alguns eu não tenho conta aberta.

Obrigado.
@RafaelUSA7

**Comment by RafaelUSA7** [comment]
Esse abaixo funcionou apenas no NuBank e no Inter com chave de e-mail (Valor de R$ 10,00)
Framework:
`00020126500014BR.GOV.BCB.PIX0128RAFAEL.AZEREDO.DEV@GMAIL.COM520400005303986540410.05802BR5917Rafael de Azeredo6007TAUBATE62080504RJV46304A5F2`
Site GerarPIX:
`00020126500014BR.GOV.BCB.PIX0128rafael.azeredo.dev@gmail.com520400005303986540510.005802BR5917Rafael de Azeredo6007TAUBATE62080504RJV46304D23A`

Esse abaixo com o valor com 10,52 não funcionou nem no NuBank, com o valor de 10,50 funcionou

Com valor de R$ 10,52
Framework:
`00020126500014BR.GOV.BCB.PIX0128RAFAEL.AZEREDO.DEV@GMAIL.COM520400005303986541810.5200004577636725802BR5917Rafael de Azeredo6007TAUBATE62080504RJV463049F4D`
Site GerarPIX:
`00020126500014BR.GOV.BCB.PIX0128rafael.azeredo.dev@gmail.com520400005303986540510.525802BR5917Rafael de Azeredo6007TAUBATE62080504RJV46304CEAA`

Com valor de R$ 10,50

Framework:
`00020126500014BR.GOV.BCB.PIX0128RAFAEL.AZEREDO.DEV@GMAIL.COM520400005303986540410.55802BR5917Rafael de Azeredo6007TAUBATE62080504RJV463041413`
Site GerarPIX: 
`00020126500014BR.GOV.BCB.PIX0128rafael.azeredo.dev@gmail.com520400005303986540510.505802BR5917Rafael de Azeredo6007TAUBATE62080504RJV4630484C0`

**Comment by mattnicee7** [comment]
Fiz uma alteração no código da geração do texto. Peço que dê uma conferida, testei e agora está gerando exatamente igual ao site citado.

[Last Release](https://github.com/mattnicee7/PixQRCodeGenerator/releases/tag/1.1.2)

Siga o tutorial da README para poder ter o projeto atualizado em seu projeto.

Aguardo retorno, obrigado.
@RafaelUSA7

**Comment by mattnicee7** [comment]
> Esse abaixo funcionou apenas no NuBank e no Inter com chave de e-mail (Valor de R$ 10,00) Framework: `00020126500014BR.GOV.BCB.PIX0128RAFAEL.AZEREDO.DEV@GMAIL.COM520400005303986540410.05802BR5917Rafael de Azeredo6007TAUBATE62080504RJV46304A5F2` Site GerarPIX: `00020126500014BR.GOV.BCB.PIX0128rafael.azeredo.dev@gmail.com520400005303986540510.005802BR5917Rafael de Azeredo6007TAUBATE62080504RJV46304D23A`
> 
> Esse abaixo com o valor com 10,52 não funcionou nem no NuBank, com o valor de 10,50 funcionou
> 
> Com valor de R$ 10,52 Framework: `00020126500014BR.GOV.BCB.PIX0128RAFAEL.AZEREDO.DEV@GMAIL.COM520400005303986541810.5200004577636725802BR5917Rafael de Azeredo6007TAUBATE62080504RJV463049F4D` Site GerarPIX: `00020126500014BR.GOV.BCB.PIX0128rafael.azeredo.dev@gmail.com520400005303986540510.525802BR5917Rafael de Azeredo6007TAUBATE62080504RJV46304CEAA`
> 
> Com valor de R$ 10,50
> 
> Framework: `00020126500014BR.GOV.BCB.PIX0128RAFAEL.AZEREDO.DEV@GMAIL.COM520400005303986540410.55802BR5917Rafael de Azeredo6007TAUBATE62080504RJV463041413` Site GerarPIX: `00020126500014BR.GOV.BCB.PIX0128rafael.azeredo.dev@gmail.com520400005303986540510.505802BR5917Rafael de Azeredo6007TAUBATE62080504RJV4630484C0`

Esses últimos 2 exemplos de código copia e cola (valor de R$10,50 e R$10,52), o suposto problema era que o código estava gerando 10.5 de valor sendo que era pra gerar 10.50, para sanar o problema coloquei um [Formatador de Decimais](https://github.com/mattnicee7/PixQRCodeGenerator/commit/94d368fc40a9e5377e78e8e69c0b8d3f16165719#diff-666d040b6675ff29ce3749c434d91134888e49e5d9b88ee793fee436d1627904R19) e está gerando de forma correta agora, inclusive o tamanho (length) do texto (10.50), que antes estava resultando em 4 de length (por que estava considerando somente 10.5), agora está resultando na forma certa, que é 5 caracteres (10.50).

Também foi encontrado um outro problema analisando mais a fundo, a chave PIX [era colocada em Caixa Alta](https://github.com/mattnicee7/PixQRCodeGenerator/commit/94d368fc40a9e5377e78e8e69c0b8d3f16165719#diff-0d98e5ca55be1987e8a324345d03c53bada8e1d299b5e6c81c56ed4a56f1ff74R166), e assim formava um Checksum (4 ultimos digitos da chave pix copia e cola gerada) diferente do que o site gerava. Acredito que iria funcionar do mesmo jeito, mas vamos deixar de forma correta e igual aos outros, não é mesmo?

Aguardo retorno com os devidos testes, muito obrigado.
@RafaelUSA7

**Comment by RafaelUSA7** [comment]
Testei aqui com os bancos que eu tenho e funcionou perfeito em todos (NuBank, Neon, Inter e PagBank)
Amanhã meu irmão e meu pai irão me ajudar a testar nos bancos que eles tem (incluíndo o Santander) ai te dou um retorno caso não funcione em algum

Muito obrigado por disponibilizar esse projeto

**Comment by mattnicee7** [comment]
> Testei aqui com os bancos que eu tenho e funcionou perfeito em todos (NuBank, Neon, Inter e PagBank)
> Amanhã meu irmão e meu pai irão me ajudar a testar nos bancos que eles tem (incluíndo o Satander) ai te dou um retorno caso não funcione em algum
> 
> Muito obrigado por disponibilizar esse projeto

Muito obrigado pela colaboração no projeto. 😎😄

**Comment by RafaelUSA7** [comment]
Bancos testados funcionando perfeitamente:
Itau
Caixa
Mercado Pago
Santander
NuBank
Neon
Inter
PagBank
Digio
Bradesco
C6Bank
