### ISSUE TITLE
QRCode Parou de Funcionar

### ISSUE THREAD

**Issue by RafaelAthosPrime** [mattnicee7/PixQRCodeGenerator#2]
Bom dia, hoje recebi mensagem de alguns clientes meus informando que o QRCode do PIX não está funcionando, pode ter tido alteração de alguma regra nos bancos

**Comment by mattnicee7** [comment]
Bom dia. Você pode estar fazendo alguns testes e estar me repassando? Consigo verificar hoje mesmo.

**Comment by RafaelAthosPrime** [comment]
Posso sim, segue abaixo alguns testes que fiz

Chave PIX CNPJ Banco Inter: 52535246000161
00020126360014BR.GOV.BCB.PIX01145253524600016152040000530398654047.505802BR598RJV SOFT6006Brasil621405103506DD4697630498E7

Chave PIX Aleatória Banco Inter: ba8fba8d-1b48-4417-a2ff-3e5e486b1bb5
00020126580014BR.GOV.BCB.PIX0136ba8fba8d-1b48-4417-a2ff-3e5e486b1bb552040000530398654047.505802BR598RJV SOFT6006Brasil6214051068035441536304BDED

Chave PIX E-mail Banco Cora: dev@rjvsoft.com
00020126370014BR.GOV.BCB.PIX0115dev@rjvsoft.com52040000530398654047.505802BR598RJV SOFT6006Brasil62140510A8DF586E056304FEEA

- Chave PIX E-mail e CPF Nubank Funciona

**Comment by RafaelAthosPrime** [comment]
Código utilizado na geração do QRCode
![image](https://github.com/mattnicee7/PixQRCodeGenerator/assets/147651057/211baaef-d6c0-431a-be57-b1e25b1a3bcd)

**Comment by RafaelAthosPrime** [comment]
Fiz alguns testes comparando com o QRCode gerado pelo gerarpix.com.br e parece que está com um número a menos

Site GerarPIX
00020126360014BR.GOV.BCB.PIX01145253524600016152040000530398654047.505802BR5908RJV SOFT6006BRASIL62140510DFF7F3E08B63049DF7

Lib:
00020126360014BR.GOV.BCB.PIX01145253524600016152040000530398654047.505802BR598RJV SOFT6006BRASIL6214051013F2DFF8C86304C751

![image](https://github.com/mattnicee7/PixQRCodeGenerator/assets/147651057/8cb332f6-c66f-4b59-bcf3-9f2f918400c7)

**Comment by RafaelAthosPrime** [comment]
https://openpix.com.br/qrcode/scanner/

Site GerarPIX:
![image](https://github.com/mattnicee7/PixQRCodeGenerator/assets/147651057/c7fda048-a2ff-47a3-be98-5bba366631c3)

Lib:
![image](https://github.com/mattnicee7/PixQRCodeGenerator/assets/147651057/c317f218-99b8-4b20-aae2-d1c66130d1eb)

**Comment by mattnicee7** [comment]
@RafaelAthosPrime Rafael, entendi o erro já e soltei uma versão que provavelmente irá resolver o erro. Poderia testar por gentileza?

**Comment by mattnicee7** [comment]
Versão 1.1.3

**Comment by RafaelAthosPrime** [comment]
> @RafaelAthosPrime Rafael, entendi o erro já e soltei uma versão que provavelmente irá resolver o erro. Poderia testar por gentileza?

Opa valeu já irei testar aqui

**Comment by RafaelAthosPrime** [comment]
Corrigido muito obrigado
